# Generated by Django 4.2.3 on 2023-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applications_applied',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jobs_posted',
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
