# Generated by Django 4.2.3 on 2023-07-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
