# Generated by Django 4.2.3 on 2023-07-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Declined'), (0, 'Pending'), (1, 'Accepted'), (2, 'Withdrawn')], default=0),
        ),
    ]
