# Generated by Django 4.2.3 on 2023-07-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
