# Generated by Django 4.2.3 on 2023-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_description_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
