# Generated by Django 4.2.3 on 2023-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_description_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
