# Generated by Django 4.2.3 on 2023-07-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_count', models.IntegerField()),
                ('regular_expression', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StringInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_input', models.CharField(max_length=1000)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch1.testcases')),
            ],
        ),
    ]
