# Generated by Django 4.2.3 on 2023-07-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(default='e', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StringInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_input', models.CharField(max_length=1000)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='ch1.testcases')),
            ],
            options={
                'ordering': ['case'],
            },
        ),
    ]
