# Generated by Django 4.2.3 on 2023-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringinputs',
            name='string_input',
            field=models.CharField(max_length=1000),
        ),
    ]
