# Generated by Django 4.2.3 on 2023-07-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='regular_expression',
            new_name='regex',
        ),
    ]
