# Generated by Django 4.2.3 on 2023-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_applied_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
